### ISSUE TITLE
Misconfiguration for display with KittenBot Bridge

### ISSUE THREAD

**Issue by gbraad** [KittenBot/kittenbot-docs#8]
The following is configured as part of the bootloader for Bridge
```
PIN_DISPLAY_BL = PIN_D5
PIN_DISPLAY_CS = PB12
PIN_DISPLAY_DC = PIN_D3
PIN_DISPLAY_MOSI = PIN_D6
PIN_DISPLAY_RST = PIN_D2
PIN_DISPLAY_SCK = PIN_D4
```

but this seems odd, as `PIN_DISPLAY_CS` refers to a CPU pin `PB12`. This is defined several times as being:

```
PIN_D6 = PB15
PIN_D6 = PB12
PIN_D6 = PA02
```

as `D6` and therefore overwitten by `PA02`.

**Comment by gbraad** [comment]
@xmeow @smfox10 Anyone?

**Comment by xmeow** [comment]
@gbraad please ref the header file for a correct pin defined for bridge bootloader.
https://gitee.com/Kittenbot/uf2-samdx1/blob/kitten-bridge/boards/kittenbot-bridge/board_config.h

Actually we already have upcomming arcade-shield working under this setup.

**Comment by gbraad** [comment]
@xmeow That is very good news... certainly would like to test this too.
I"ll have a look at those repos and see what I can find and help to add in the docs.

**Comment by gbraad** [comment]
Latest firmware works with the Arcade Shield
